name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Docker image
        run: docker build -t face-recog .

      - name: Build APK inside container
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          face-recog \
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/apk/debug/*.apk
